name: project-iris

networks:
  iris-network:
    driver: bridge

volumes:
  ollama:
  openwebui:


services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0
    volumes:
      - ollama:/root/.ollama
    networks:
      - iris-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
  lobe-chat:
    image: lobehub/lobe-chat:latest
    ports:
      - "3210:3210"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    networks:
      - iris-network

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "3211:8080"
    volumes:
      - openwebui:/app/backend/data
    networks:
      - iris-network
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
